from sqlalchemy.orm import Session

from app.services.retrieval_service import retrieve_standards
from app.graph.review_graph import graph

from app.database.models import (
    CodeSubmission,
    ReviewReport,
)


def create_review(
    db: Session,
    language: str,
    code: str,
    context: str
):
    # Save submitted code
    submission = CodeSubmission(
        language=language,
        code=code,
        context=context
    )

    db.add(submission)
    db.commit()
    db.refresh(submission)

    # Retrieve relevant coding standards
    standards = retrieve_standards(
        db=db,
        code=code
    )

    retrieved_context = "\n\n".join(
        [
            f"""
Title: {item.title}
Category: {item.category}

Content:
{item.content}
"""
            for item in standards
        ]
    )

    print("Retrieved Standards:")
    print(retrieved_context)

    print("Calling LangGraph...")

    # Execute LangGraph workflow
    result = graph.invoke(
        
        {
            "db": db,
            "submission_id": submission.id,
            "language": language,
            "code": code,
            "context": context or "",
            "standards": retrieved_context
        }
    )

    print("Graph Result:")
    print(result)

    review = result["saved_review"]

    return review
    # Extract review generated by LLM node
    review_data = result["review_result"]

    # Save review report
    # review = ReviewReport(
    #     id=result["review_id"],
    #     submission_id=submission.id,
    #     score=review_data["score"],
    #     summary=review_data["summary"],
    #     issues=review_data["issues"]
    # )

    # db.add(review)
    # db.commit()
    # db.refresh(review)

    # return review